version: "3.1"

services:
  development:
    image: postgres:12.3-alpine
    ports:
      - 35432:5432
    environment:
      POSTGRES_USER: quest
      POSTGRES_PASSWORD: quest
      POSTGRES_DB: quest
      TZ: "GMT+8"
      PGTZ: "GMT+8"

  test:
    image: postgres:12.3-alpine
    ports:
      - 54320:5432
    environment:
      POSTGRES_USER: quest
      POSTGRES_PASSWORD: quest
      POSTGRES_DB: quest_test
      TZ: "GMT+8"
      PGTZ: "GMT+8"

  pgadmin:
    image: dpage/pgadmin4:4.29
    environment:
      PGADMIN_DEFAULT_EMAIL: quest@quest.com
      PGADMIN_DEFAULT_PASSWORD: quest
    ports:
      - 3002:80
    depends_on:
      - development
    links:
      - development:development
    restart: on-failure
