version: "3.1"

services:
  development:
    image: postgres:12.3-alpine
    ports:
      - 35432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

  test:
    image: postgres:12.3-alpine
    ports:
      - 54320:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

  pgadmin:
    image: dpage/pgadmin4:4.29
    environment:
      PGADMIN_DEFAULT_EMAIL: user@user.com
      PGADMIN_DEFAULT_PASSWORD: pass
    ports:
      - 3002:80
    depends_on:
      - development
    links:
      - development:development
    restart: on-failure
