version: "3.1"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=development
      - POSTGRES_USERNAME=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_HOST=postgres://db
      - POSTGRES_PORT=5432
      - POSTGRES_NAME=db
      - POSTGRES_DISABLE_SSL=true
      - JWT_SECRET=teamQuestIsTheBest
    depends_on:
      - db

  db:
    image: postgres:12.3-alpine
    ports:
      - 35432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

  db_test:
    image: postgres:12.3-alpine
    ports:
      - 54320:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
