version: "3.1"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=production
      - POSTGRES_USERNAME=user
      - POSTGRES_PASSWORD=teamQuest123!@#
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_NAME=prod_db
      - POSTGRES_DISABLE_SSL=true
      - JWT_SECRET=teamQuestIsTheBest
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:12.3-alpine
    ports:
      - 54345:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: teamQuest123!@#
      POSTGRES_DB: prod_db
